export const songs = [
  {
    id: 1,
    title: 'OutSide',
    artist: 'Calvin Haris',
    image: require('../assets/images/outside.jpeg'),
    artwork: require('../assets/images/outside.jpeg'),
    url: require('../assets/songs/outside.mp3'),
    duration: 207,
  },
  {
    id: 2,
    title: 'Brooklyn',
    artist: 'Unknown',
    image: require('../assets/images/brooklyn.jpeg'),
    artwork: require('../assets/images/brooklyn.jpeg'),
    url: require('../assets/songs/brooklyn.mp3'),
    duration: 135,
  },
  {
    id: 3,
    title: 'Butter',
    artist: 'BTS',
    image: require('../assets/images/butter.png'),
    artwork: require('../assets/images/butter.png'),
    url: require('../assets/songs/butter.mp3'),
    duration: 192,
  },
  {
    id: 4,
    title: "Don't Let me down",
    artist: 'ChainSmokers',
    image: require('../assets/images/letme.jpeg'),
    artwork: require('../assets/images/letme.jpeg'),
    url: require('../assets/songs/let-me-down.mp3'),
    duration: 202,
  },
];
